### ISSUE TITLE
Deepslate ignored

### ISSUE THREAD

**Issue by deadspidervenom** [vlad2305m/Sound-Physics#4]
Deepslate acts like air, letting sound through. I keep hearing skeletons on the other side of walls without echo. (also get echo)

**Comment by vlad2305m** [comment]
Not for me. The mod checks if the side sound goes through is a full square to muffle it using minecraft's method. And minecraft's ray tracing. Please make a proper bug report that allows to recreate the issue. (Seriously, just attach settings file and state what version you are using with what other mods (or even your save, if I'll not be able to do this with all above). I can only fix something if it exists for me). 
The only other issue I can think of is sound reflections leaking through block corners, but what you describe doesn't seem like it.

**Comment by deadspidervenom** [comment]
ill do some testing, as it is a modpack it may be a unintended conflict. Just to confirm does the mod need to be server side as well as client side? ( i ask cause i only have it client side)

Also apologies for the lack of info, version of the mod was 1.1.1, as for settings only thing i did was your recommended setting. No crash occurred so no report to really give, and log showed nothing out of place involving your mod.

The reason i did not include any info the first time is i thought it may have been a oversight as deepslate only spawns in pockets in vanilla, however in the pack i setup, it spawns similar to how it is intended.

**Comment by vlad2305m** [comment]
Oh yeah. Forgot to mention. This mod specifically ignores everything below y=0 as there is nothing there anyway. Hold on while I add a setting to change min Y.

**Comment by vlad2305m** [comment]
Should be fixed now.
